version: '2'
services:
  web:
    build: ./readlists
    ports:
      - "80:3000"
    depends_on:
      - db
      - scraper
      - calibre
  scraper:
    build: ./scraper

  calibre:
    image: denouche/node-calibre-api

  db:
    image: postgres
