default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  # Set by docker-compose or prod provider
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: readlists_development

test:
  <<: *default
  database: readlists_test

production:
  <<: *default
  database: readlists_production
